quarkus.http.port=8081
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.devservices.enabled=false
quarkus.hibernate-orm.schema-management.strategy=none
security.password.bcrypt-cost=${BCRYPT_COST:12}
security.jwt.secret=${JWT_SECRET}
security.jwt.issuer=${JWT_ISSUER:agencia-bancaria-api}
security.jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS:900}
smallrye.jwt.verify.secretkey=${JWT_VERIFY_JWK}
smallrye.jwt.sign.key=${JWT_VERIFY_JWK}
smallrye.jwt.verify.algorithm=HS256
mp.jwt.verify.issuer=${JWT_ISSUER:agencia-bancaria-api}
