quarkus.http.port=8081
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.devservices.enabled=false
quarkus.hibernate-orm.schema-management.strategy=none
security.password.bcrypt-cost=${BCRYPT_COST:12}
